"""Add event-driven scenario models and fields

Revision ID: d70eb5ac026e
Revises: 005
Create Date: 2026-05-15 20:46:50.736819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd70eb5ac026e'
down_revision: Union[str, None] = '005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bank_accounts_last_reconciled_at', table_name='bank_accounts')
    op.drop_column('bank_accounts', 'statement_balance')
    op.drop_column('bank_accounts', 'reconciliation_status')
    op.drop_column('bank_accounts', 'last_reconciled_at')
    op.drop_column('bank_accounts', 'statement_date')
    op.drop_column('bank_accounts', 'balance_discrepancy_amount')
    op.drop_column('bank_accounts', 'last_statement_document_id')
    op.add_column('budget_scenarios', sa.Column('goal_id', sa.UUID(), nullable=True))
    op.add_column('budget_scenarios', sa.Column('scenario_type', sa.String(length=50), nullable=False))
    op.add_column('budget_scenarios', sa.Column('simulation_horizon_months', sa.Integer(), nullable=False))
    op.add_column('budget_scenarios', sa.Column('strategy_type', sa.String(length=50), nullable=False))
    op.add_column('budget_scenarios', sa.Column('feasibility_score', sa.Numeric(precision=5, scale=2), nullable=True))
    op.create_foreign_key(None, 'budget_scenarios', 'goals', ['goal_id'], ['id'])
    op.drop_index('idx_transactions_direction_type', table_name='transactions')
    op.create_index('idx_transactions_user_direction', 'transactions', ['user_id', 'direction_type'], unique=False)
    op.create_index(op.f('ix_transactions_direction_type'), 'transactions', ['direction_type'], unique=False)
    op.drop_index('ix_upload_history_statement_date_from_file', table_name='upload_history')
    op.drop_column('upload_history', 'reconciliation_status')
    op.drop_column('upload_history', 'balance_extraction_attempted')
    op.drop_column('upload_history', 'statement_balance_extracted')
    op.drop_column('upload_history', 'processing_completed_at')
    op.drop_column('upload_history', 'extracted_closing_balance')
    op.drop_column('upload_history', 'processing_duration_seconds')
    op.drop_column('upload_history', 'processing_started_at')
    op.drop_column('upload_history', 'statement_date_from_file')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload_history', sa.Column('statement_date_from_file', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('upload_history', sa.Column('processing_started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('upload_history', sa.Column('processing_duration_seconds', sa.NUMERIC(precision=10, scale=0), autoincrement=False, nullable=True))
    op.add_column('upload_history', sa.Column('extracted_closing_balance', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('upload_history', sa.Column('processing_completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('upload_history', sa.Column('statement_balance_extracted', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('upload_history', sa.Column('balance_extraction_attempted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('upload_history', sa.Column('reconciliation_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_index('ix_upload_history_statement_date_from_file', 'upload_history', ['statement_date_from_file'], unique=False)
    op.drop_index(op.f('ix_transactions_direction_type'), table_name='transactions')
    op.drop_index('idx_transactions_user_direction', table_name='transactions')
    op.create_index('idx_transactions_direction_type', 'transactions', ['direction_type'], unique=False)
    op.drop_constraint(None, 'budget_scenarios', type_='foreignkey')
    op.drop_column('budget_scenarios', 'feasibility_score')
    op.drop_column('budget_scenarios', 'strategy_type')
    op.drop_column('budget_scenarios', 'simulation_horizon_months')
    op.drop_column('budget_scenarios', 'scenario_type')
    op.drop_column('budget_scenarios', 'goal_id')
    op.add_column('bank_accounts', sa.Column('last_statement_document_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('bank_accounts', sa.Column('balance_discrepancy_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('bank_accounts', sa.Column('statement_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('bank_accounts', sa.Column('last_reconciled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('bank_accounts', sa.Column('reconciliation_status', postgresql.ENUM('PENDING', 'RECONCILED', 'DISCREPANCY', 'NOT_APPLICABLE', name='reconciliationstatus'), autoincrement=False, nullable=True))
    op.add_column('bank_accounts', sa.Column('statement_balance', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.create_index('ix_bank_accounts_last_reconciled_at', 'bank_accounts', ['last_reconciled_at'], unique=False)
    # ### end Alembic commands ###
